#pragma once
#include <string>
#include <unordered_map>
#include <algorithm>
#include <stdexcept>
#include <cctype>

enum class Key
{
    Unknown,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Escape,
    Space,
    Enter,
    Tab,
    Left,
    Right,
    Up,
    Down,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    PrintScreen,
    ScrollLock,
    Pause,
    Insert,
    Home,
    PageUp,
    Delete,
    End,
    PageDown,
    Backspace,
    CapsLock,
    NumLock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    Divide,
    Multiply,
    Subtract,
    Add,
    Decimal,
    LeftCtrl,
    RightCtrl,
    LeftShift,
    RightShift,
    LeftAlt,
    RightAlt,
    LeftSuper,
    RightSuper,
    Menu,
    Application
};

// Инициализация маппинга строка -> enum

inline const auto mapfrom = std::unordered_map<std::string, Key>({{"unknown", Key::Unknown},
                                                                  {"a", Key::A},
                                                                  {"b", Key::B},
                                                                  {"c", Key::C},
                                                                  {"d", Key::D},
                                                                  {"e", Key::E},
                                                                  {"f", Key::F},
                                                                  {"g", Key::G},
                                                                  {"h", Key::H},
                                                                  {"i", Key::I},
                                                                  {"j", Key::J},
                                                                  {"k", Key::K},
                                                                  {"l", Key::L},
                                                                  {"m", Key::M},
                                                                  {"n", Key::N},
                                                                  {"o", Key::O},
                                                                  {"p", Key::P},
                                                                  {"q", Key::Q},
                                                                  {"r", Key::R},
                                                                  {"s", Key::S},
                                                                  {"t", Key::T},
                                                                  {"u", Key::U},
                                                                  {"v", Key::V},
                                                                  {"w", Key::W},
                                                                  {"x", Key::X},
                                                                  {"y", Key::Y},
                                                                  {"z", Key::Z},
                                                                  {"num0", Key::Num0},
                                                                  {"num1", Key::Num1},
                                                                  {"num2", Key::Num2},
                                                                  {"num3", Key::Num3},
                                                                  {"num4", Key::Num4},
                                                                  {"num5", Key::Num5},
                                                                  {"num6", Key::Num6},
                                                                  {"num7", Key::Num7},
                                                                  {"num8", Key::Num8},
                                                                  {"num9", Key::Num9},
                                                                  {"escape", Key::Escape},
                                                                  {"esc", Key::Escape},
                                                                  {"space", Key::Space},
                                                                  {"enter", Key::Enter},
                                                                  {"tab", Key::Tab},
                                                                  {"left", Key::Left},
                                                                  {"right", Key::Right},
                                                                  {"up", Key::Up},
                                                                  {"down", Key::Down},
                                                                  {"f1", Key::F1},
                                                                  {"f2", Key::F2},
                                                                  {"f3", Key::F3},
                                                                  {"f4", Key::F4},
                                                                  {"f5", Key::F5},
                                                                  {"f6", Key::F6},
                                                                  {"f7", Key::F7},
                                                                  {"f8", Key::F8},
                                                                  {"f9", Key::F9},
                                                                  {"f10", Key::F10},
                                                                  {"f11", Key::F11},
                                                                  {"f12", Key::F12},
                                                                  {"printscreen", Key::PrintScreen},
                                                                  {"prtsc", Key::PrintScreen},
                                                                  {"scrolllock", Key::ScrollLock},
                                                                  {"pause", Key::Pause},
                                                                  {"insert", Key::Insert},
                                                                  {"ins", Key::Insert},
                                                                  {"home", Key::Home},
                                                                  {"pageup", Key::PageUp},
                                                                  {"pgup", Key::PageUp},
                                                                  {"delete", Key::Delete},
                                                                  {"del", Key::Delete},
                                                                  {"end", Key::End},
                                                                  {"pagedown", Key::PageDown},
                                                                  {"pgdn", Key::PageDown},
                                                                  {"backspace", Key::Backspace},
                                                                  {"capslock", Key::CapsLock},
                                                                  {"numlock", Key::NumLock},
                                                                  {"numpad0", Key::Numpad0},
                                                                  {"numpad1", Key::Numpad1},
                                                                  {"numpad2", Key::Numpad2},
                                                                  {"numpad3", Key::Numpad3},
                                                                  {"numpad4", Key::Numpad4},
                                                                  {"numpad5", Key::Numpad5},
                                                                  {"numpad6", Key::Numpad6},
                                                                  {"numpad7", Key::Numpad7},
                                                                  {"numpad8", Key::Numpad8},
                                                                  {"numpad9", Key::Numpad9},
                                                                  {"divide", Key::Divide},
                                                                  {"multiply", Key::Multiply},
                                                                  {"subtract", Key::Subtract},
                                                                  {"add", Key::Add},
                                                                  {"decimal", Key::Decimal},
                                                                  {"leftctrl", Key::LeftCtrl},
                                                                  {"rightctrl", Key::RightCtrl},
                                                                  {"leftshift", Key::LeftShift},
                                                                  {"rightshift", Key::RightShift},
                                                                  {"leftalt", Key::LeftAlt},
                                                                  {"rightalt", Key::RightAlt},
                                                                  {"leftsuper", Key::LeftSuper},
                                                                  {"rightsuper", Key::RightSuper},
                                                                  {"menu", Key::Menu},
                                                                  {"application", Key::Application}});



inline const auto maptostr = std::unordered_map<Key, std::string>({{Key::Unknown, "Unknown"},                                                                   
                                                                         {Key::A, "A"},
                                                                         {Key::B, "B"},
                                                                         {Key::C, "C"},
                                                                         {Key::D, "D"},
                                                                         {Key::E, "E"},
                                                                         {Key::F, "F"},
                                                                         {Key::G, "G"},
                                                                         {Key::H, "H"},
                                                                         {Key::I, "I"},
                                                                         {Key::J, "J"},
                                                                         {Key::K, "K"},
                                                                         {Key::L, "L"},
                                                                         {Key::M, "M"},
                                                                         {Key::N, "N"},
                                                                         {Key::O, "O"},
                                                                         {Key::P, "P"},
                                                                         {Key::Q, "Q"},
                                                                         {Key::R, "R"},
                                                                         {Key::S, "S"},
                                                                         {Key::T, "T"},
                                                                         {Key::U, "U"},
                                                                         {Key::V, "V"},
                                                                         {Key::W, "W"},
                                                                         {Key::X, "X"},
                                                                         {Key::Y, "Y"},
                                                                         {Key::Z, "Z"},
                                                                         {Key::Num0, "Num0"},
                                                                         {Key::Num1, "Num1"},
                                                                         {Key::Num2, "Num2"},
                                                                         {Key::Num3, "Num3"},
                                                                         {Key::Num4, "Num4"},
                                                                         {Key::Num5, "Num5"},
                                                                         {Key::Num6, "Num6"},
                                                                         {Key::Num7, "Num7"},
                                                                         {Key::Num8, "Num8"},
                                                                         {Key::Num9, "Num9"},
                                                                         {Key::Escape, "Escape"},
                                                                         {Key::Space, "Space"},
                                                                         {Key::Enter, "Enter"},
                                                                         {Key::Tab, "Tab"},
                                                                         {Key::Left, "Left"},
                                                                         {Key::Right, "Right"},
                                                                         {Key::Up, "Up"},
                                                                         {Key::Down, "Down"},
                                                                         {Key::F1, "F1"},
                                                                         {Key::F2, "F2"},
                                                                         {Key::F3, "F3"},
                                                                         {Key::F4, "F4"},
                                                                         {Key::F5, "F5"},
                                                                         {Key::F6, "F6"},
                                                                         {Key::F7, "F7"},
                                                                         {Key::F8, "F8"},
                                                                         {Key::F9, "F9"},
                                                                         {Key::F10, "F10"},
                                                                         {Key::F11, "F11"},
                                                                         {Key::F12, "F12"},
                                                                         {Key::PrintScreen, "PrintScreen"},
                                                                         {Key::ScrollLock, "ScrollLock"},
                                                                         {Key::Pause, "Pause"},
                                                                         {Key::Insert, "Insert"},
                                                                         {Key::Home, "Home"},
                                                                         {Key::PageUp, "PageUp"},
                                                                         {Key::Delete, "Delete"},
                                                                         {Key::End, "End"},
                                                                         {Key::PageDown, "PageDown"},
                                                                         {Key::Backspace, "Backspace"},
                                                                         {Key::CapsLock, "CapsLock"},
                                                                         {Key::NumLock, "NumLock"},
                                                                         {Key::Numpad0, "Numpad0"},
                                                                         {Key::Numpad1, "Numpad1"},
                                                                         {Key::Numpad2, "Numpad2"},
                                                                         {Key::Numpad3, "Numpad3"},
                                                                         {Key::Numpad4, "Numpad4"},
                                                                         {Key::Numpad5, "Numpad5"},
                                                                         {Key::Numpad6, "Numpad6"},
                                                                         {Key::Numpad7, "Numpad7"},
                                                                         {Key::Numpad8, "Numpad8"},
                                                                         {Key::Numpad9, "Numpad9"},
                                                                         {Key::Divide, "Divide"},
                                                                         {Key::Multiply, "Multiply"},
                                                                         {Key::Subtract, "Subtract"},
                                                                         {Key::Add, "Add"},
                                                                         {Key::Decimal, "Decimal"},
                                                                         {Key::LeftCtrl, "LeftCtrl"},
                                                                         {Key::RightCtrl, "RightCtrl"},
                                                                         {Key::LeftShift, "LeftShift"},
                                                                         {Key::RightShift, "RightShift"},
                                                                         {Key::LeftAlt, "LeftAlt"},
                                                                         {Key::RightAlt, "RightAlt"},
                                                                         {Key::LeftSuper, "LeftSuper"},
                                                                         {Key::RightSuper, "RightSuper"},
                                                                         {Key::Menu, "Menu"},
                                                                         {Key::Application, "Application"}});

// Нормализация строки (нижний регистр + удаление неалфавитных символов)
static std::string normalizeString(const std::string &str)
{
    std::string result;
    for (unsigned char c : str)
    {
        if (std::isalnum(c))
        {
            result += std::tolower(c);
        }
    }
    return result;
}
// Преобразование строки в Key
static Key KeyfromString(const std::string &str)
{
    std::string normalized = normalizeString(str);
    auto it = mapfrom.find(normalized);

    if (it != mapfrom.end())
    {
        return Key(it->second);
    }
    return Key(Key::Unknown);
}

// Преобразование в строку
static std::string KeytoString(Key value) 
{
    auto it = maptostr.find(value);
    if (it != maptostr.end())
    {
        return it->second;
    }
    return "Unknown";
}
